package com.lawfirm.law.firm.dto;

import com.lawfirm.law.firm.model.Client;
import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.time.Period;
import java.time.ZoneId;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface ClientMapper {
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "nonBillable", expression = "java(dto.getNonBillable() != null ? dto.getNonBillable() : false)")
    Client toEntity(ClientDetailsDTO dto);
    ClientDetailsDTO toDTO(Client entity);

    // map entity -> list item DTO for grid/listing
    ClientListResponseDTO toListDTO(Client entity);

    // map create DTO to DTO (used in controller)
    ClientDetailsDTO fromCreate(ClientCreateRequestDTO createDto);

    @AfterMapping
    default void computeAndPopulate(Client entity, @MappingTarget ClientDetailsDTO dto) {
        if (entity == null) return;
        // set generated id
        if (entity.getId() != null) dto.setId(entity.getId());
        // set createdAt from entity (generated by DB or prePersist)
        if (entity.getCreatedAt() != null) dto.setCreatedAt(entity.getCreatedAt());
        // set updatedAt from entity (new column)
        if (entity.getUpdatedAt() != null) dto.setUpdatedAt(entity.getUpdatedAt());
        // compute age
        if (entity.getBirthDate() != null) {
            int age = Period.between(entity.getBirthDate(), java.time.LocalDate.now(ZoneId.systemDefault())).getYears();
            dto.setAge(age);
        }
    }
}
